### ISSUE TITLE
Syntax error in ImageMagick command

### ISSUE THREAD

**Issue by X123M3-256** [oli414/Blender-RCT-Graphics#13]
I get a syntax error near `-opaque rgb(57,59,57)` in the ImageMagick command line. I had to escape the parenthesis to get it to work.

**Comment by oli414** [comment]
I suppose they changed the syntax in an update, I'll have to update my description with prerequisites and adjust the command, thanks!

**Comment by X123M3-256** [comment]
It's bash that's throwing the error rather than ImageMagick, parentheses are special characters and need to be escaped if they're not to be interpreted as bash code.

Also, it might be nice to wrap the ImageMagick call in a try ... except block so you can print out any error message it returns. I had to do that to track down why it wasn't working (actually, it doesn't seem to work without it, even if no exception is thrown, which is weird).

**Comment by oli414** [comment]
This has been resolved with the latest update
