### ISSUE TITLE
Camera slightly misaligned

### ISSUE THREAD

**Issue by X123M3-256** [oli414/Blender-RCT-Graphics#14]
This is the product of rendering a single 1 tile wide square:

![tile](https://user-images.githubusercontent.com/5165278/70653417-607b3180-1c4c-11ea-9488-2ff8d799c9a8.png)

It should look like this (you'll need to zoom right in to see the difference - look at the corners):

![tile2](https://user-images.githubusercontent.com/5165278/70653419-607b3180-1c4c-11ea-99f1-6bf10dee602a.png)

This probably doesn't matter if you're only using this to render custom rides, but if you are rendering sprites that have to tesselate with existing ones (like terrain, track or certain scenery items like base blocks), it's important.

This problem can be fixed by shifting the camera 1/(8√6) Blender units in the Z axis, but I can't remember if it should be shifted up or down (the computer I'm typing this from doesn't have the game, so I can't check).

**Comment by oli414** [comment]
Well found! I rotated the camera and moved it away from the world center, I wonder if the original tools simply gave different results or if Simon really moved the camera up by a fraction.

I'll have to change that though

**Comment by X123M3-256** [comment]
I don't know. I had to fudge this in my renderer as well, it certainly seems to me that the current behaviour is more natural, but if you want to match the vanilla tiles you need to change it. I can work out which way you need to move the camera when I'm on my desktop.

**Comment by magnusg** [comment]
To match the vanilla objects - important for building blocks etc. - the correct camera rig z value is 139.73878 (add 0.05103103 to the predefined value)

**Comment by oli414** [comment]
Thanks! I ended up adding 0.0510309375 after recalculating the tile height in Blender units (1.63299)

![tile1](https://user-images.githubusercontent.com/2348094/159122466-95763c87-509c-4cec-94b9-78dee982ae6e.png)

**Comment by oli414** [comment]
Resolved in the latest update
