### ISSUE TITLE
Porting to Blender 2.83 - what will it take?

### ISSUE THREAD

**Issue by Ryder17z** [oli414/Blender-RCT-Graphics#15]
As a beginner user I can't wrap my head around blender 2.79 so i'm curious of what's required to make this plugin work for later versions.

**Comment by oli414** [comment]
One of the biggest focuses of this setup was the aim to mimic the original graphics. To achieve this the "Blender Render" scanline renderer was used, which is inline with what Simon Foster would have used to render the original graphics.

Unfortunately, the 2.8 update completely removed this render method in favor of a ray-traced, and hybrid solution. Along with that some major changes were made to the way layers work.

I have been unable to make Eevee or Cycles render in a way that ticks all the boxes for a render to look and feel like an original object. Frutiemax created a setup for post 2.8 Blender, which does a pretty good a job. But in my honest opinion, it doesn't quite match up to what we were able to achieve with Blender Render.

**Comment by oli414** [comment]
This add-on will remain a Blender 2.79 add-on
