### ISSUE TITLE
Include "x" and "x_offset"

### ISSUE THREAD

**Issue by spacek531** [oli414/Blender-RCT-Graphics#31]
OpenRCT2's object sprite parser uses "x" and "y" which the plugin is designed for. OpenRCT2's sprite cli builder uses "x_offset" and "y_offset" for reasons unknown. This tool could output both and I won't have to replace-all to add the _offset every time.

**Comment by oli414** [comment]
What are you using the sprite compiler for?

**Comment by spacek531** [comment]
Making an LGX because it's faster than copying the giant sprite.json into an object

**Comment by oli414** [comment]
The add-on already has build in support for making optimized sprite files
Same applies to the creation of your object.json, you should not have to copy anything there's build in support for generating the final file.
